//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HeaderNamespace", IsNullable=false)]
public partial class nagłówek {
    
    private autor[] autorField;
    
    private string opisField;
    
    private System.DateTime dataAktualizacjiField;
    
    private uint kluczField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("autor")]
    public autor[] autor {
        get {
            return this.autorField;
        }
        set {
            this.autorField = value;
        }
    }
    
    /// <uwagi/>
    public string opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataAktualizacji {
        get {
            return this.dataAktualizacjiField;
        }
        set {
            this.dataAktualizacjiField = value;
        }
    }
    
    /// <uwagi/>
    public uint klucz {
        get {
            return this.kluczField;
        }
        set {
            this.kluczField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HeaderNamespace", IsNullable=false)]
public partial class autor {
    
    private string imięField;
    
    private string nazwiskoField;
    
    private uint nrIndeksuField;
    
    private string idField;
    
    /// <uwagi/>
    public string imię {
        get {
            return this.imięField;
        }
        set {
            this.imięField = value;
        }
    }
    
    /// <uwagi/>
    public string nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/NumericalTypesNamespace")]
    public uint nrIndeksu {
        get {
            return this.nrIndeksuField;
        }
        set {
            this.nrIndeksuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/NumericalTypesNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/NumericalTypesNamespace", IsNullable=false)]
public partial class cena {
    
    private cenaWaluta walutaField;
    
    private decimal valueField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public cenaWaluta waluta {
        get {
            return this.walutaField;
        }
        set {
            this.walutaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/NumericalTypesNamespace")]
public enum cenaWaluta {
    
    /// <uwagi/>
    zł,
    
    /// <uwagi/>
    euro,
    
    /// <uwagi/>
    dolar,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public enum gatunek {
    
    /// <uwagi/>
    rock,
    
    /// <uwagi/>
    metalcore,
    
    /// <uwagi/>
    metal,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("progressive-death-metal")]
    progressivedeathmetal,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("punk-rock")]
    punkrock,
    
    /// <uwagi/>
    rap,
    
    /// <uwagi/>
    pop,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("hip-hop")]
    hiphop,
    
    /// <uwagi/>
    inny,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public partial class płytoteka {
    
    private nagłówek nagłówekField;
    
    private zbiór zbiórField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/HeaderNamespace")]
    public nagłówek nagłówek {
        get {
            return this.nagłówekField;
        }
        set {
            this.nagłówekField = value;
        }
    }
    
    /// <uwagi/>
    public zbiór zbiór {
        get {
            return this.zbiórField;
        }
        set {
            this.zbiórField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public partial class zbiór {
    
    private płyta[] płytaField;
    
    private string nazwaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("płyta")]
    public płyta[] płyta {
        get {
            return this.płytaField;
        }
        set {
            this.płytaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public partial class płyta {
    
    private string tytułField;
    
    private string[] wykonawcaField;
    
    private decimal liczbaUtworówField;
    
    private System.DateTime dataWydaniaField;
    
    private cena cenaField;
    
    private gatunek gatunekField;
    
    private płytaUtwory utworyField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string tytuł {
        get {
            return this.tytułField;
        }
        set {
            this.tytułField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("wykonawca")]
    public string[] wykonawca {
        get {
            return this.wykonawcaField;
        }
        set {
            this.wykonawcaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/NumericalTypesNamespace")]
    public decimal liczbaUtworów {
        get {
            return this.liczbaUtworówField;
        }
        set {
            this.liczbaUtworówField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dataWydania {
        get {
            return this.dataWydaniaField;
        }
        set {
            this.dataWydaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/NumericalTypesNamespace")]
    public cena cena {
        get {
            return this.cenaField;
        }
        set {
            this.cenaField = value;
        }
    }
    
    /// <uwagi/>
    public gatunek gatunek {
        get {
            return this.gatunekField;
        }
        set {
            this.gatunekField = value;
        }
    }
    
    /// <uwagi/>
    public płytaUtwory utwory {
        get {
            return this.utworyField;
        }
        set {
            this.utworyField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
public partial class płytaUtwory {
    
    private utwór[] listaField;
    
    private string nazwaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("utwór", IsNullable=false)]
    public utwór[] lista {
        get {
            return this.listaField;
        }
        set {
            this.listaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public partial class utwór {
    
    private string tytułUtworuField;
    
    private string czasTrwaniaField;
    
    private utwórCodec codecField;
    
    private short bitrateField;
    
    public utwór() {
        this.codecField = utwórCodec.mp3;
        this.bitrateField = ((short)(320));
    }
    
    /// <uwagi/>
    public string tytułUtworu {
        get {
            return this.tytułUtworuField;
        }
        set {
            this.tytułUtworuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/NumericalTypesNamespace", DataType="token")]
    public string czasTrwania {
        get {
            return this.czasTrwaniaField;
        }
        set {
            this.czasTrwaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(utwórCodec.mp3)]
    public utwórCodec codec {
        get {
            return this.codecField;
        }
        set {
            this.codecField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(short), "320")]
    public short bitrate {
        get {
            return this.bitrateField;
        }
        set {
            this.bitrateField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
public enum utwórCodec {
    
    /// <uwagi/>
    mp3,
    
    /// <uwagi/>
    flac,
    
    /// <uwagi/>
    ogg,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/OurNamespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/OurNamespace", IsNullable=false)]
public partial class lista {
    
    private utwór[] utwórField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("utwór")]
    public utwór[] utwór {
        get {
            return this.utwórField;
        }
        set {
            this.utwórField = value;
        }
    }
}
